<a href="https://colab.research.google.com/github/Kazim0071/Deep-Learning-with-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **00. Pytorch Fundamentals**

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensores
### Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/2.14/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# vecctor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([
    [
        [1, 2 ,3],
        [3, 6, 9],
        [2, 4, 5]
    ],
    [
        [11, 12, 13],
        [13, 16, 19],
        [12, 14, 15]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[11, 12, 13],
         [13, 16, 19],
         [12, 14, 15]]])

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])

In [14]:
TENSOR.ndim

3

### **Random tensors**

Why Random tensors?

Random tensors are important because the way many neural network learn iis taht they start with tenors full of random numebrs and adjust thoes random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor - https://docs.pytorch.org/docs/2.14/generated/torch.rand.html

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1336, 0.4633, 0.4163, 0.5177],
        [0.1417, 0.0801, 0.3923, 0.4439],
        [0.3897, 0.9061, 0.6064, 0.6712]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 Big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in Computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # What datatype is the tensor (eg. float32 or float16)
    device=None, # What device is your tensors on (eg, CPU, CUDA)
    requires_grad=False # Weather or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - todo get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7032, 0.6109, 0.0302, 0.5822],
        [0.6787, 0.6969, 0.6293, 0.9834],
        [0.1655, 0.9675, 0.1533, 0.7812]])

In [32]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7032, 0.6109, 0.0302, 0.5822],
        [0.6787, 0.6969, 0.6293, 0.9834],
        [0.1655, 0.9675, 0.1533, 0.7812]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divition
* Matrix multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor

tensor([1, 2, 3])

In [36]:
# Subtract 10
tensor -10

tensor([-9, -8, -7])

In [37]:
# Try our pythorch in build finctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

 ### Matrix Multiplication

 Two main ways of performing multiplication in neural networks and deep learning:

 1. Element-wise multiplication
 2. Matrix Multiplication (dot product)

 More information on multiplication matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

 There are two rules that performing matrix multiplication needs to satisfy:

 1. The **inner dimentions** must match:
 * `(3, 2) @ (3, 2)` won't work
 * `(2, 3) @ (3, 2)` will work
 * `(3, 2) @ (2, 3)` will work

 2. The resulting matrix has the shape of the **outer dimentions:**
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [39]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.8839, 0.8508],
        [0.3009, 0.3507]])

In [40]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value = 0

for i in range (len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 800 µs, sys: 102 µs, total: 902 µs
Wall time: 7.96 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 878 µs, sys: 112 µs, total: 990 µs
Wall time: 3.89 ms


tensor(14)

### One of the most common errors in deep learning is shape errors

In [47]:
# Shape for matrix multiplication
tensor_A = torch.tensor([

        [1, 2],
        [3, 4],
        [5, 6],

])

tensor_B = torch.tensor([

        [7, 10],
        [8, 11],
        [9, 12]

])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issue, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimentions of a given tensor.

In [49]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [50]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [51]:
# The matrix multiplication operation works when tensor_b is transposed
print(f"original shapes: tesnor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimenstions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

original shapes: tesnor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimenstions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [52]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the min
torch.min(x), x.min

(tensor(1), <function Tensor.min>)

In [54]:
# Find the max
torch.max(x), x.max

(tensor(91), <function Tensor.max>)

In [55]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [57]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(1)

In [60]:
# Find the position in tensor that has a maximum value with argmax()
x.argmax()

tensor(9)

In [61]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined Shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeez - removes all `1` dimentions form a tensor
* Unsqueez - add a `1` dimention to a target tensor
* Permute - Return a view of the input with dimentions premuted (swapped) in a certain way

In [62]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add an extra dimention
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
# Changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
# Stack tensors on the top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:
# x = torch.zeros(2, 1, 2, 1, 2)
# x.size()
# torch.Size([2, 1, 2, 1, 2])
# y = torch.squeeze(x)
# y.size()
# torch.Size([2, 2, 2])
# y = torch.squeeze(x, 0)
# y.size()
# torch.Size([2, 1, 2, 1, 2])
# y = torch.squeeze(x, 1)
# y.size()
# torch.Size([2, 2, 1, 2])
# y = torch.squeeze(x, (1, 2, 3))
# torch.Size([2, 2, 2])

In [75]:
# torch.squeeze() - removes all single dimentions from a target tensor

print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# Remove extra dimentions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [77]:
# torch.unsqueeze() - adds a single dimention to a taget tensor at a specific dim (dimention)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_squeezed}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
